name: audible_maps_asu
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_mapbox_navigation: ^0.2.2
  flutter_rating_bar: ^4.0.1
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  location: ^5.0.3
  mapbox_gl: ^0.16.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - config/.env
